### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by ghost** [MiCode/Notes#13]
D/OpenGLRenderer( 6105): Enabling debug mode 0
W/InputManagerService(  148): Starting input on non-focused client com.android.internal.view.IInputMethodClient$Stub$Proxy@41680458 (uid=10017 pid=374)
I/ActivityManager(  148): Displayed net.micode.notes/.ui.NotesListActivity: +666ms (total +1m35s793ms)
D/dalvikvm( 6105): GC_CONCURRENT freed 100K, 3% free 11468K/11719K, paused 12ms+3ms
E/ActivityThread( 6105): Failed to find provider info for notes
D/dalvikvm(  222): GC_CONCURRENT freed 442K, 28% free 10357K/14279K, paused 2ms+3ms
E/ActivityThread( 6105): Failed to find provider info for notes
E/ActivityThread( 6105): Failed to find provider info for notes
I/ActivityManager(  148): START {act=android.intent.action.SEARCH flg=0x10000000 cmp=net.micode.notes/.ui.NoteEditActivity (has extras)} from pid 6105
W/InputManagerService(  148): Starting input on non-focused client com.android.internal.view.IInputMethodClient$Stub$Proxy@415318f8 (uid=10021 pid=6105)
D/dalvikvm(  222): GC_CONCURRENT freed 376K, 28% free 10378K/14279K, paused 2ms+3ms
E/NoteEditActivity( 6105): Intent not specified action, should not support
W/ActivityManager(  148): Duplicate finish request for ActivityRecord{41765688 net.micode.notes/.ui.NoteEditActivity}
W/InputManagerService(  148): Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@41536ab0
D/AndroidRuntime( 6105): Shutting down VM
W/dalvikvm( 6105): threadid=1: thread exiting with uncaught exception (group=0x40a5d1f8)
D/dalvikvm( 6105): GC_CONCURRENT freed 159K, 3% free 12014K/12295K, paused 2ms+3ms
E/AndroidRuntime( 6105): FATAL EXCEPTION: main
E/AndroidRuntime( 6105): java.lang.NullPointerException
E/AndroidRuntime( 6105):    at net.micode.notes.ui.NoteEditActivity.clearSettingState(NoteEditActivity.java:466)
E/AndroidRuntime( 6105):    at net.micode.notes.ui.NoteEditActivity.onPrepareOptionsMenu(NoteEditActivity.java:485)
E/AndroidRuntime( 6105):    at android.app.Activity.onPreparePanel(Activity.java:2462)
E/AndroidRuntime( 6105):    at com.android.internal.policy.impl.PhoneWindow.preparePanel(PhoneWindow.java:416)
E/AndroidRuntime( 6105):    at com.android.internal.policy.impl.PhoneWindow.invalidatePanelMenu(PhoneWindow.java:739)
E/AndroidRuntime( 6105):    at com.android.internal.policy.impl.PhoneWindow$1.run(PhoneWindow.java:2833)
E/AndroidRuntime( 6105):    at android.os.Handler.handleCallback(Handler.java:605)
E/AndroidRuntime( 6105):    at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime( 6105):    at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 6105):    at android.app.ActivityThread.main(ActivityThread.java:4424)
E/AndroidRuntime( 6105):    at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 6105):    at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime( 6105):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
E/AndroidRuntime( 6105):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
E/AndroidRuntime( 6105):    at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(  148):   Force finishing activity net.micode.notes/.ui.NotesListActivity
W/ActivityManager(  148): Activity pause timeout for ActivityRecord{4173d258 net.micode.notes/.ui.NotesListActivity}

**Comment by ghost** [comment]
测试机器Nexus S（9023），bug重现的方法：首先删除所有的标签，然后点击机器下面的“搜索”按键，随便调用一个输入法输入随意的字母或者内容，则出现上述问题，直接挂掉！

**Comment by sharpdevelop** [comment]
Thank you for your hard work, I have fix it.
